const donors = [
  {
    id: 0,
    name: "Sharful Islam",
    sex: "Male",
    location: "Mirpur",
    blood_group: "A+",
    days_lastdonate: 130,
    status: "available donors",
    donated: ["Shariar", "Nabir", "Shila", "Rahman"],
    cell: "01534516158",
  },
  {
    id: 1,
    name: "Sabbir Chowdhury",
    sex: "Male",
    location: "Agargaon",
    blood_group: "A-",
    days_lastdonate: 157,
    status: "available donors",
    donated: ["Sumon", "Sharif", "Shila", "Rumu"],
    cell: "01711546213",
  },
  {
    id: 2,
    name: "Feroza Rima",
    sex: "Female",
    location: "Farmgate",
    blood_group: "AB+",
    days_lastdonate: 146,
    status: "available donors",
    donated: ["Tushar", "Momin", "Rizvi"],
    cell: "01918546258",
  },
  {
    id: 3,
    name: "Nishad Hasan",
    sex: "Male",
    location: "Dhanmondi",
    blood_group: "B+",
    days_lastdonate: 137,
    status: "available donors",
    donated: ["Munna", "Suchona", "Rekha"],
    cell: "01714346524",
  },
  {
    id: 4,
    name: "Sewli Hori",
    sex: "Feale",
    location: "Azimpur",
    blood_group: "B+",
    days_lastdonate: 72,
    status: "Not Ready to Donate",
    donated: ["Promoy", "Sibbir"],
    cell: "01562854963",
  },
  {
    id: 5,
    name: "Ratul Kazii",
    sex: "Male",
    location: "Uttara",
    blood_group: "O+",
    days_lastdonate: 172,
    status: "available donors",
    donated: ["Swarna", "Redwan", "Razib", "Roman"],
    cell: "01819758953",
  },
  {
    id: 6,
    name: "Sazid Arafat",
    sex: "Male",
    location: "Worry",
    blood_group: "O-",
    days_lastdonate: 180,
    status: "available donors",
    donated: ["Shariar", "Nabir", "Shila", "Rahman"],
    cell: "01717426458",
  },
  {
    id: 7,
    name: "Rakib Hossaiin",
    sex: "Male",
    location: "Khilgaon",
    blood_group: "AB+",
    days_lastdonate: 122,
    status: "available donors",
    donated: ["Kabir", "Nora", "Hena", "khalid"],
    cell: "01716354956",
  },
  {
    id: 8,
    name: "Nipun Khanom",
    sex: "Female",
    location: "Badda",
    blood_group: "A+",
    days_lastdonate: 70,
    status: "Not Ready to Donate",
    donated: ["Hridoy", "Soma", "Sagar"],
    cell: "01789545741",
  },
  {
    id: 9,
    name: "Israt Mukti",
    sex: "Female",
    location: "Kuril",
    blood_group: "A-",
    days_lastdonate: 65,
    status: "Not Ready to Donate",
    donated: ["Shariar", "Nabir", "Shila", "Rahman"],
    cell: "01321758956",
  },
  {
    id: 10,
    name: "Raja Khan",
    sex: "Male",
    location: "Mohammadpur",
    blood_group: "AB+",
    days_lastdonate: 34,
    status: "Not Ready to Donate",
    donated: ["Shariar", "Nabir", "Shila", "Rahman"],
    cell: "01414325368",
  },
  {
    id: 11,
    name: "Nima Rahman",
    sex: "Female",
    location: "Mirpur",
    blood_group: "AB-",
    days_lastdonate: 28,
    status: "Not Ready to Donate",
    donated: ["Rafkat", "Sathi", "Nisha"],
    cell: "01199875963",
  },
  {
    id: 12,
    name: "Kasfia Khatun",
    sex: "Female",
    location: "Dhanmondi",
    blood_group: "O+",
    days_lastdonate: 37,
    status: "Not Ready to Donate",
    donated: ["Suchona", "Talib", "Manik", "Shefa", "Neha", "Rubel", "Sabuj"],
    cell: "01511684956",
  },
  {
    id: 13,
    name: "Manjur Morshed",
    sex: "Male",
    location: "Gulisthan",
    blood_group: "B+",
    days_lastdonate: 138,
    status: "available donors",
    donated: ["Rashed"],
    cell: "01922845762",
  },
  {
    id: 14,
    name: "Karim Faisal",
    sex: "Male",
    location: "Segunbagicha",
    blood_group: "B+",
    days_lastdonate: 127,
    status: "available donors",
    donated: ["Rasy", "Swapon"],
    cell: "01452785463",
  },
  {
    id: 15,
    name: "Any Sharker",
    sex: "Female",
    location: "Farmgate",
    blood_group: "O+",
    days_lastdonate: 121,
    status: "available donors",
    donated: ["Rumky", "Shiraj"],
    cell: "01971735915",
  },
  {
    id: 16,
    name: "Fahim ul Haque",
    sex: "Male",
    location: "Mohammadpur",
    blood_group: "B+",
    days_lastdonate: 127,
    status: "available donors",
    donated: ["Shafi", "Mahmudul", "Anabia"],
    cell: "01341957351",
  },
  {
    id: 17,
    name: "Redwan Shaikh",
    sex: "Male",
    location: "Farmgate",
    blood_group: "B+",
    days_lastdonate: 128,
    status: "available donors",
    donated: ["Shitajul"],
    cell: "01711428651",
  },
  {
    id: 18,
    name: "Rebeka Sultana",
    sex: "Female",
    location: "Mirpur",
    blood_group: "A+",
    days_lastdonate: 122,
    status: "available donors",
    donated: ["Rahim"],
    cell: "01324123458",
  },
  {
    id: 19,
    name: "Tushar Abdullah",
    sex: "Male",
    location: "Purbachal",
    blood_group: "B+",
    days_lastdonate: 139,
    status: "available donors",
    donated: ["Kebla", "Babul", "Nabi"],
    cell: "01725123456",
  },
];
